package webTest;
// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.apache.commons.io.FileUtils;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

import java.io.File;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.Matchers.is;

public class AlterarNomePerfilEveclass {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @BeforeEach
    public void setUp() {
        WebDriverManager.chromedriver().setup();

        ChromeOptions options = new ChromeOptions();
        options.addArguments("--remote-allow-origins=*");

        // Aponta onde está o Chrome Driver
        // System.setProperty("webdriver.chrome.driver", "drivers/chrome/chromedriver.exe");
        driver = new ChromeDriver(options); // Instancia / Liga o Chrome Driver
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS); // Espera até que o elemento seja encotrado
    }
    @AfterEach
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void testeAlterarNomeEveclass() throws InterruptedException, IOException {
        // Iniciando Teste acessando o site Testando Eveclass
        driver.get("https://testando.eveclass.com/pt");
        driver.manage().window().maximize();
        // Aciona o botão "Começar Agora"
        driver.findElement(By.cssSelector(".button-custom:nth-child(4) > .button-text > span > span")).click();
        // Aciona o botão "Entrar"
        driver.findElement(By.cssSelector("#support-action > span > span > span")).click();


        // Seleciona o Input "Email" e inseri os valores
        WebElement inputEmail = driver.findElement(By.cssSelector("input[data-vv-as='Email'][type='Email']"));
        inputEmail.sendKeys("cristianobonfim@souunisuam.com.br");

        // Seleciona o Input "password" e inseri os valores
        WebElement inputSenha = driver.findElement(By.cssSelector("input[type='password']"));
        inputSenha.sendKeys("Cristi@no31");

        // Aciona o botão "Entrar"
        driver.findElement(By.xpath("//*[@id=\"auth-panel\"]/div[2]/div/div/div/div/div[2]/div/form/div[2]/button")).click();

        driver.findElement(By.cssSelector("div.user-avatar.avatar-initials")).click();

        driver.findElement(By.cssSelector(".fal.fa-user-circle")).click();

        // Seleciona o Input "Nome"
        WebElement inputNome = driver.findElement(By.cssSelector("input[data-vv-as='Nome'][type='text']"));

        // Seleciona todo o texto no campo de entrada de texto
        inputNome.sendKeys(Keys.CONTROL + "a");
        inputNome.sendKeys(Keys.BACK_SPACE);
        // Insere o texto "cris" no campo de entrada de texto
        inputNome.sendKeys("cris");

        // Aciona o botão "Salvar Alterações"
        driver.findElement(By.xpath("//*[@id=\"account-panel\"]/div[2]/div/div/div/div/div[1]/section/form/button")).click();
        Thread.sleep(3000); // espera por 4 segundos

        // Verifica se o texto esperado é igual ao texto atual
        assertThat(driver.findElement(By.id("swal2-title")).getText(), is("Perfil editado com successo!"));

        // Gera um print-screen do final do Teste para verificação
        File screenshot = ((TakesScreenshot) driver).getScreenshotAs(OutputType.FILE);
        FileUtils.copyFile(screenshot, new File("src/test/resources/utils/print/evidenciaAlterarNome.png"));
    }
}

