package webTest;
// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

import java.util.HashMap;
import java.util.Map;
public class CriarNovoCursoEveclass {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @BeforeEach
    public void setUp() {
        WebDriverManager.chromedriver().setup();

        ChromeOptions options = new ChromeOptions();
        options.addArguments("--remote-allow-origins=*");

        // Aponta onde está o Chrome Driver
        // System.setProperty("webdriver.chrome.driver", "drivers/chrome/chromedriver.exe");
        driver = new ChromeDriver(options); // Instancia / Liga o Chrome Driver
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @AfterEach
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void testeCriarNovoCurso() throws InterruptedException {
        // Iniciando Teste acessando o site Testando Eveclass
        driver.get("https://testando.eveclass.com/pt");
        driver.manage().window().setSize(new Dimension(1580, 840));
        // Aciona o botão "Começar Agora"
        driver.findElement(By.cssSelector(".button-custom:nth-child(4) > .button-text > span > span")).click();

        // Aciona o botão "Entrar"
        driver.findElement(By.cssSelector("#support-action > span > span > span")).click();
        Thread.sleep(2000); // espera por 2 segundos

        // Seleciona o Input "Email" e inseri os valores
        WebElement inputEmail = driver.findElement(By.cssSelector("input[data-vv-as='Email'][type='Email']"));
        String rotuloEmail = inputEmail.getAttribute("data-vv-as");
        System.out.println(rotuloEmail); // imprime "Seu Email"
        inputEmail.sendKeys("email admin");

        // Seleciona o Input "password" e inseri os valores
        WebElement inputSenha = driver.findElement(By.cssSelector("input[type='password']"));
        String rotuloSenha = inputSenha.getAttribute("type");
        System.out.println(rotuloSenha); // imprime "Sua Senha"
        inputSenha.sendKeys("senha");

        // Aciona o botão "Entrar"
        driver.findElement(By.xpath("//*[@id=\"auth-panel\"]/div[2]/div/div/div/div/div[2]/div/form/div[2]/button/span/span")).click();
        Thread.sleep(5000); // espera por 5 segundos

        // Aciona o botão "Cursos"
        driver.findElement(By.linkText("Cursos")).click();
        Thread.sleep(2000); // espera por 2 segundos

        // Aciona o botão "Novo Curso"
        driver.findElement(By.xpath("//*[@id=\"scroll-container\"]/div/div/div/div[2]/div[1]/div/div/div[2]/a/span/span/span")).click();
        Thread.sleep(2000); // espera por 2 segundos

        // Seleciona o elemento de rádio pelo texto da descrição
        WebElement radio = driver.findElement(By.xpath("//h3[contains(text(), 'Módulos')]/ancestor::div[@class='card-radio-option']"));
        radio.click();

        // Aciona o botão "Prosseguir"
        WebElement button = driver.findElement(By.cssSelector("button[class='button  button-default'] i[class='icon-right fas fa-arrow-right']"));
        button.click();
        Thread.sleep(2000); // espera por 2 segundos

        // Seleciona opção "Cronograma"
        WebElement cronograma = driver.findElement(By.cssSelector("i.far.fa-user-clock"));
        cronograma.click();

        // Aciona o botão "Prosseguir"
        WebElement button2 = driver.findElement(By.cssSelector("button[type='submit']"));
        button2.click();
        Thread.sleep(2000); // espera por 2 segundos

        // Seleciona o Input "telefone" e inseri os valores
        WebElement inputNome = driver.findElement(By.cssSelector("input[data-vv-as='Nome'][type='text']"));
        String rotuloTelefone = inputNome.getAttribute("data-vv-as");
        System.out.println(rotuloTelefone); // imprime "Seu Telefone"
        inputNome.sendKeys("Teste Novo Curso");

        // Aciona o botão "Salvar"
        WebElement botaoSalvar = driver.findElement(By.xpath("//span[contains(text(), 'Salvar')]"));
        botaoSalvar.click();
        Thread.sleep(2000); // espera por 2 segundos

        // Procurando o Nome do Curso para verficação se o Curso foi Criado
        WebElement element = driver.findElement(By.xpath("//h1[text()='Teste Novo Curso']"));
        // Verifica se o elemento foi encontrado
        if (element.isDisplayed()) {
            System.out.println("O elemento foi encontrado. Curso Criado com Sucesso!");
        } else {
            System.out.println("O elemento não foi encontrado.");
        }
    }
}
