package webTest;
// Generated by Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
public class CriarContaEveclass {

    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @BeforeEach
    public void setUp() {
        WebDriverManager.chromedriver().setup();

        ChromeOptions options = new ChromeOptions();
        options.addArguments("--remote-allow-origins=*");

        // Aponta onde está o Chrome Driver
        // System.setProperty("webdriver.chrome.driver", "drivers/chrome/chromedriver.exe");
        driver = new ChromeDriver(options); // Instancia / Liga o Chrome Driver
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @AfterEach
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void testeCriarConta() throws InterruptedException {
        driver.get("https://testando.eveclass.com/pt");
        driver.manage().window().setSize(new Dimension(1580, 840));
        driver.findElement(By.cssSelector(".button-custom:nth-child(4) > .button-text > span > span")).click();
        driver.findElement(By.cssSelector("#main-action > .button-text > span > span")).click();
        Thread.sleep(3000); // espera por 3 segundos

        WebElement inputNomeCompleto = driver.findElement(By.cssSelector("input[data-vv-as='Seu nome completo'][type='text']"));
        String rotuloNomeCompleto = inputNomeCompleto.getAttribute("data-vv-as");
        System.out.println(rotuloNomeCompleto); // imprime "Seu nome completo"
        Thread.sleep(3000); // espera por 3 segundos
        inputNomeCompleto.sendKeys("Cristiano");
        Thread.sleep(3000); // espera por 3 segundos

        WebElement inputEmail = driver.findElement(By.cssSelector("input[data-vv-as='Seu email'][type='text']"));
        String rotuloEmail = inputEmail.getAttribute("data-vv-as");
        System.out.println(rotuloEmail); // imprime "Seu Email"
        inputEmail.sendKeys("cristiaaai@gmail.com");
        Thread.sleep(3000); // espera por 3 segundos

        WebElement inputConfirmeEmail = driver.findElement(By.cssSelector("input[data-vv-as='Confirme seu email'][type='text']"));
        String rotuloConfirmeEmail = inputConfirmeEmail.getAttribute("data-vv-as");
        System.out.println(rotuloConfirmeEmail); // imprime "Seu Email repetido"
        inputConfirmeEmail.sendKeys("cristiaaai@gmail.com");

        driver.findElement(By.cssSelector(".button-text > span")).click();
        Thread.sleep(8000); // espera por 10 segundos

        WebElement inputSenha = driver.findElement(By.cssSelector("input[type='password']"));
        String rotuloSenha = inputSenha.getAttribute("type");
        System.out.println(rotuloSenha); // imprime "Sua Senha"
        inputSenha.sendKeys("123456789");
        Thread.sleep(4000); // espera por 3 segundos

        List<WebElement> inputsSenha = driver.findElements(By.cssSelector("input[type='password']"));

        if (inputsSenha.size() > 1) {
            WebElement segundoInputSenha = inputsSenha.get(1);
            segundoInputSenha.sendKeys("123456789");
            System.out.println(inputsSenha); // imprime "Sua Senha repetida"
        } else {
            System.out.println("Apenas um campo de senha encontrado.");
        }
        Thread.sleep(3000); // espera por 3 segundos
        driver.findElement(By.cssSelector(".button-text > span")).click();
        Thread.sleep(7000); // espera por 7 segundos
        System.out.println("Conta Criada com Sucesso"); // imprime a Sucesso do Teste
    }
}
